services:
  app:
    build: .
    container_name: browtoppro-container
    ports:
      - "1032:8765"  # Map user ID port (1032) to container port (8765)
    volumes:
      - /var/run/utmp:/var/run/utmp:ro  # for getting the host's current users
      - /var/log/wtmp:/var/log/wtmp:ro  # for getting the host's last users
      - /var/log/syslog:/var/log/syslog # for getting the host's syslog
    privileged: true  # To get system-level information
    pid: "host"  # Share the process ID namespace with the host
    restart: always

