version: '3.8'

services:
  server_monitor:
    build: .
    ports:
      - "8765:8765"   # Sunucunun portunu dışarı aç
    volumes:
      - .:/app        # Proje dosyalarını container içine eşleştir
